### ISSUE TITLE
Related to aoc-badges-action

### ISSUE THREAD

**Issue by J0B10** [k2bd/advent-readme-stars#2]
Just found your nice looking repo. I recognized it poped up the day I shared my [aoc-badges-action](https://github.com/J0B10/aoc-badges-action/) on reddit which has many similarities to this. 

So I'm curious, did you took inspiration from it? 😅 

One user even did get confused by the similarities of the repo and reported an error with your reop on my reddit post: xD
https://www.reddit.com/r/adventofcode/comments/r6go1m/comment/hmwk903/

If you reused any code from my repo, pls adhere to MIT License and give credit.

Have a great Advent!

**Comment by k2bd** [comment]
Hiya, I have seen your badges action (and use it on [my advent of code repo's README](https://github.com/k2bd/advent-of-code#advent-of-code)!) - It's a very cool action, and got me thinking about other ways to have actions maintain progress info in AoC READMEs. It was definitely an inspiration!

I have not reused code from that repo, of course I would only do so under the conditions of its license.

With your permission, I am happy to add a 'Related Projects' section to the README linking to your action. It'd be awesome if you did the same on yours, but that's up to you

**Comment by J0B10** [comment]
Sounds like a good idea 👍
