### ISSUE TITLE
Speed up action container build

### ISSUE THREAD

**Issue by fspoettel** [k2bd/advent-readme-stars#7]
Hey, thank you for building this!

I noticed that the action takes a while to build each time a workflow using it runs. For me, [it's around 35-40 seconds](https://github.com/fspoettel/advent-of-code-rust/actions) that are added to each run. With a cron workflow dispatch, this can add up.

I looked at the logs and noticed that the Dockerfile installs poetry in the container. I tested a [simpler install method](https://github.com/fspoettel/advent-readme-stars/commit/f8f46f1bea0d8bf8a8d9b706332780e3d7eefe53) on my fork, which brought the docker build time [down by around 10 seconds](https://github.com/fspoettel/advent-readme-stars/actions/runs/3474009446/jobs/5806683291#step:3:9).

Would you accept a PR for this?

**Comment by k2bd** [comment]
@fspoettel that would be awesome, thank you!
